import type { AnimationStepKind } from "./types"

export const ANIMATION_DURATIONS: Record<AnimationStepKind, number> = {
  SUMMON_FLY_IN: 600,
  UNIT_LUNGE: 200,
  UNIT_IMPACT: 250,
  DAMAGE_NUMBER: 400,
  HEALTH_BAR_UPDATE: 300,
  UNIT_DEATH: 500,
  SPELL_FLASH: 350,
  PHASE_BANNER: 900,
  TURN_INDICATOR: 700,
  PLAYER_DAMAGE_SHAKE: 300,
  ACE_UNLOCK: 800,
  REVOLVE_PULSE: 400,
  UNIT_PRIMED_GLOW: 600,
  SPELLSHIELD_BLOCK: 400,
  ABILITY_BURST: 350,
  IDLE: 0,
}
