import { CardType, CardClass, Rarity, Keyword, TriggerType, EffectType, TargetType } from "@tcg/shared-types"
import type { UnitCardDefinition } from "@tcg/shared-types"

export const testCards: UnitCardDefinition[] = [
  {
    id: "arcane_healer",
    type: CardType.Unit,
    cost: 3,
    infuse: 2,
    attack: 2,
    health: 4,
    keywords: [],
    abilities: [
      {
        kind: "activated",
        displayName: "Mend",
        activationCost: 1,
        oncePerTurn: true,
        actions: [{ type: EffectType.HEAL, target: TargetType.ALLY_PLAYER, value: 3 }],
      },
    ],
    metadata: { rarity: Rarity.Uncommon, class: CardClass.Scholar },
  },
  {
    id: "void_reaper",
    type: CardType.Unit,
    cost: 4,
    infuse: 2,
    attack: 4,
    health: 3,
    keywords: [Keyword.Overkill],
    abilities: [
      {
        kind: "activated",
        displayName: "Soul Drain",
        activationCost: 2,
        oncePerTurn: true,
        actions: [{ type: EffectType.DEAL_DAMAGE, target: TargetType.ENEMY_UNIT, value: 3 }],
      },
    ],
    metadata: { rarity: Rarity.Rare, class: CardClass.Abyss },
  },
  {
    id: "iron_golem",
    type: CardType.Unit,
    cost: 5,
    infuse: 3,
    attack: 2,
    health: 8,
    keywords: [Keyword.Guard],
    abilities: [
      {
        kind: "activated",
        displayName: "Reinforce",
        activationCost: 2,
        oncePerTurn: true,
        actions: [{ type: EffectType.BUFF_HEALTH, target: TargetType.SELF, value: 2 }],
      },
    ],
    metadata: { rarity: Rarity.Rare, class: CardClass.Machine },
  },
  {
    id: "shadow_blade",
    type: CardType.Unit,
    cost: 3,
    infuse: 2,
    attack: 5,
    health: 2,
    keywords: [Keyword.Charge, Keyword.Lifesteal],
    abilities: [
      {
        kind: "triggered",
        trigger: TriggerType.ON_ATTACK,
        actions: [{ type: EffectType.DEAL_DAMAGE, target: TargetType.ENEMY_PLAYER, value: 1 }],
      },
    ],
    metadata: { rarity: Rarity.Rare, class: CardClass.Abyss },
  },
  {
    id: "forest_shaman",
    type: CardType.Unit,
    cost: 4,
    infuse: 2,
    attack: 2,
    health: 5,
    keywords: [],
    abilities: [
      {
        kind: "triggered",
        trigger: TriggerType.ON_SUMMON,
        actions: [{ type: EffectType.DRAW_CARD }],
      },
      {
        kind: "activated",
        displayName: "Wild Growth",
        activationCost: 2,
        oncePerTurn: true,
        actions: [{ type: EffectType.BUFF_HEALTH, target: TargetType.ALLY_UNIT, value: 3 }],
      },
    ],
    metadata: { rarity: Rarity.Uncommon, class: CardClass.Scholar },
  },
  {
    id: "berserker",
    type: CardType.Unit,
    cost: 5,
    infuse: 3,
    attack: 6,
    health: 3,
    keywords: [],
    abilities: [
      {
        kind: "triggered",
        trigger: TriggerType.ON_ATTACK,
        actions: [{ type: EffectType.BUFF_ATTACK, target: TargetType.SELF, value: 2 }],
      },
      {
        kind: "activated",
        displayName: "Bloodrage",
        activationCost: 3,
        oncePerTurn: true,
        actions: [{ type: EffectType.DEAL_DAMAGE, target: TargetType.ANY_UNIT, value: 4 }],
      },
    ],
    metadata: { rarity: Rarity.Rare, class: CardClass.Warrior },
  },
  {
    id: "barrier_knight",
    type: CardType.Unit,
    cost: 3,
    infuse: 2,
    attack: 2,
    health: 3,
    keywords: [Keyword.Barrier],
    metadata: { rarity: Rarity.Common, class: CardClass.Warrior },
  },
  {
    id: "quick_striker",
    type: CardType.Unit,
    cost: 3,
    infuse: 2,
    attack: 4,
    health: 2,
    keywords: [Keyword.Charge, Keyword.QuickAttack],
    metadata: { rarity: Rarity.Uncommon, class: CardClass.Warrior },
  },
]
