export { getCard, getAllCards, registerCard } from "./registry"
export { INVINCIBLE_STARTER_DECK } from "./starter-decks"
export { validateDeck, DECK_SIZE, MAX_COPIES } from "./deck-validator"
export { warriorCards } from "./cards/warriors"
export { spellCards } from "./cards/spells"
export { legendaryCards } from "./cards/legendary"
export { testCards } from "./cards/test-cards"
export { getCardLocale } from "./locales/index"
export { presentationRegistry } from "./presentation"
